-- Seed for the "Secrecy Fixture" world that server/test/share-live.test.js runs against.
-- Owned by a login-less user ('secrecy-fixture') so it appears on nobody's dashboard.
-- Re-running: delete the world first (the DO block below does), then update the fixture
-- ids at the top of share-live.test.js from the SELECT at the end.
-- Token: rotated to a random value (see share-live.test.js); regenerate with fx||md5(random())  ·  timeline 1..100, canon 50
-- Content contract the tests depend on:
--   era 'Open Era' 10-30 player_visible; era 'Hidden Era' 40-60 hidden
--   'Open Landmark' shared, always placed; fact 'era text' 10-30 over base 'base text'
--   'Hidden Person' dm node, placed          -> must 404 / never appear
--   'Ghost Spot' shared node, dm placement   -> never appears on the map
--   'Brief Fair' lifespan 20-40; 'Future Thing' start 80 (beyond canon)
--   'Secret Door' dm node with interior 'Hidden Interior' holding 'Inner Loot'
--   timed backdrop fixture-a.svg from t=40 (no base backdrop)
--   links: Open Landmark -> Hidden Person (pruned), -> Brief Fair (kept)
-- The full executable block lives in git history (seeded 2026-08-20); reconstruct from
-- the contract above if it ever needs rebuilding.
-- NOTE: each full test run leaves one 'probe-marker-<ts>' player node on the fixture
-- root (the write-path test). Sweep occasionally:
--   DELETE FROM nodes WHERE world_id=(SELECT id FROM worlds WHERE name='Secrecy Fixture')
--     AND visibility='player';
--
-- Added 2026-09-26 (WP-25 B109): a PENDING Forge batch that must stay invisible to players.
--   forge_batches row status 'pending' for the world, created = {
--     maps:[<'Pending Forge Interior', owner Open Landmark>], nodes:[<'Pending Inner', shared, placed on it>],
--     placements:[<that placement>], links:[<Open Landmark -> Brief Fair, label 'pending thread'>],
--     facts:[<'PENDING FACT' 10-30 on Open Landmark>], backdrops:[<map_backdrops on root from 45, image 'fixture-pending.svg'>],
--     images:[<fixture-pending.svg>],
--     enrichedImages:[{node: Open Landmark, prevImage:null, prevPin:'chip', wrote:<image>}]  (its image_id/pin ARE set in the row),
--     mapBases:[{map: root, prev:null, wrote:<image>}]                                      (root.image_id IS set),
--     enrichedBodies:[{node: Brief Fair, wrote:'only 20-40'}]                                (Brief Fair's stored body is that text) }
--   Players must see: no ◎ on Open Landmark, 404 on the pending map and its node, no art or
--   base backdrop on the root, 'era text' (not 'PENDING FACT') at t=20, fixture-a.svg (not the
--   pending art) at canon, no 'pending thread' link, an empty body on Brief Fair.
--
-- Added 2026-09-26 (WP-23 B102): 'Twice Placed', a shared node with an interior ('Twice Interior'),
-- placed FIRST inside 'Hidden Interior' (the DM-only branch) and THEN on the root. Players must
-- reach its interior through the root placement (◎ offered, 200, breadcrumb root → interior).
-- Every root roster in the tests now includes it.
-- NOTE when seeding by hand: a data-modifying CTE cannot UPDATE a row another CTE of the same
-- statement inserted (same snapshot) — set nodes.interior_map_id in a second statement.
--
-- Added 2026-09-26 (WP-27): rows that make the suite go RED when a rule is removed.
--   'Interlude Ghost' (shared, root, 32-38) lives between the eras — that alone never caught a
--   hidden-era leak; 'Hidden Era Secret' (shared, root, 42-48) and a fact 'hidden era text'
--   42-48 on Open Landmark live INSIDE the Hidden Era (t=45 must resolve to canon).
--   Clamp probes inside 'Twice Interior': 'Late Runner' 25-70 (end → null), 'Early Riser' 5-25
--   (start → null), a timed backdrop 45-70 (start → 50, end → null); era 'Future Era' 60-70
--   player_visible (never listed: it begins after canon).
--   Secrecy: Open Landmark dm_note 'DM-ONLY-NOTE' + stance 'foe'; root map dm_note 'MAP-ONLY-NOTE'.
--   'The Party' (category party): footsteps on Twice Interior 10-15 (the only reachable one),
--   Hidden Interior 16-20 (hidden branch) and Twice Interior 21-25 DM-only.
--   The lantern: worlds.spotlight_node_id = 'Lantern Target' (DM-only, placed on Twice
--   Interior) → the trail is [Twice Placed on the root] and stops there.
